config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  post 'session/signin'
  delete 'session/logout'
  get 'session/forgot_password'
  put 'session/reset_password'

  resources :users, only: [:new, :create]

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  
end

app/controllers/application_controller.rb
# application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :user_signed_in?

  def initialize
    Keycloak.proc_cookie_token = lambda do
      cookies.permanent[:keycloak_token]
    end

    super
  end

  def user_signed_in?
    access = Keycloak::Client.user_signed_in? || keycloak_controller? || new_use?
    redirect_to root_path unless access
  end

  private

    def keycloak_controller?
      Keycloak.keycloak_controller == controller_name
    end

    def new_use?
      controller_name == 'users' && (action_name == "new" || action_name == "create")
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
    def index
        @user = JSON.parse Keycloak::Client.get_userinfo
    end
end 

app/controllers/session_controller.rb
# Authentication
class SessionController < ApplicationController
  def new
    @user = User.new
  end

  def signin
    cookies.permanent[:keycloak_token] = Keycloak::Client.get_token params[:user][:email], params[:user][:password]
    redirect_to root_path if Keycloak::Client.user_signed_in?
  end

  def logout
    flash[:success] = 'See you later' if Keycloak::Client.logout
    redirect_to session_new_path
  end

  def forgot_password; end

  def reset_password
    Keycloak::Internal.forgot_password params[:user][:email], root_path
    flash[:success] = 'Please take a look at your email'
    redirect_to session_new_path
  end
end

app/controllers/users_controller.rb
# user controller
require 'rest-client'
class UsersController < ApplicationController
    def new
        @user = User.new
    end
  
    def create
      after_insert = lambda { |_user|
        flash[:success] = 'User created successfully'
        redirect_to root_path
      }

      Keycloak::Internal.create_simple_user(params[:user][:email],
                                            params[:user][:password],
                                            params[:user][:email],
                                            params[:user][:first_name],
                                            params[:user][:last_name],
                                            [],
                                            ['Public'],
                                            after_insert)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<main class="container">
  <div class="bg-light p-5 rounded">
    <h1>Bienvenue sur Yeewu</h1>
    <div class="row col-md-offset-1">
        <h4>Hello, <%=@user['name'] %></h4>
        </div>
        <div class="row col-md-offset-1">
            <div class="col-md-5">
                <%= link_to("Logout", session_logout_path, method: :delete) %>
            </div>
        </div>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keyclok</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/session/forgot_password.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="login-panel panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					My application - Forgot password
				</h3>
			</div>
			<div class="panel-body">
				<%= form_tag(url: session_reset_password_path, method: :put, data: {toggle:"validator"} ) do |f| %>
					<fieldset>
						<div class="form-group">
							<%= f.email_field '', autofocus: true, class:"form-control", id:"email", name:"email", placeholder:"Email", required: "true" %>
						</div>
						<div class=text-right>
							<%= f.submit 'Send Email', class:"btn btn-success" %>
						</div>
					</fieldset>
				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/session/new.html.erb
<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Welcome back!</h3>
              <%= simple_form_for(@user, url: session_signin_path, method: :post, data: {toggle:"validator"} ) do |f| %>
                <fieldset>
                  <div class="form-group">
                    <%= f.input :email, autofocus: true, class:"form-control", id:"email", name:"email", placeholder:"Email", required: "true" %>
                  </div>
                  <div class="form-group">
                    <%= f.input :password, autocomplete: "off", class:"form-control", id:"password", name:"password", placeholder:"Password", required: "true" %>
                  </div>
                  <div class="form-group d-flex">
                    <%= f.button :submit, "se connecter", class: "btn-primary" %>
                    <%= link_to "creer un compte", new_user_path, :class => "btn btn-outline" %>
                  </div>
                </fieldset>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Yeewu Marketplace</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to("Logout", session_logout_path, method: :delete) %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Welcome back!</h3>
              <%= simple_form_for(@user, url: users_path, method: :post, data: {toggle:"validator"} ) do |f| %>
                <fieldset>
                    <div class="form-group">
                        <%= f.input :first_name, autofocus: true, class:"form-control", id:"firstname", name:"firstname", placeholder:"Prenom", required: "true" %>
                    </div>
                    <div class="form-group">
                        <%= f.input :last_name, autofocus: true, class:"form-control", id:"lastname", name:"lastname", placeholder:"NOM", required: "true" %>
                    </div>
                    <div class="form-group">
                        <%= f.input :email, autofocus: true, class:"form-control", id:"email", name:"email", placeholder:"Email", required: "true" %>
                    </div>
                    <div class="form-group">
                        <%= f.input :password, autocomplete: "off", class:"form-control", id:"password", name:"password", placeholder:"Password", required: "true" %>
                    </div>
                    <div class="form-group">
                        <%= f.button :submit, "creer un compte", class: "btn-primary" %>
                        <%= link_to "se connecter", session_new_path, :class => "btn btn-outline" %>
                    </div>
                </fieldset>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>